config/routes.rb
Rails.application.routes.draw do
  resources :rooms, only: [:create, :show, :update] do
    resources :guesses, only: [:create, :new, :show]
    resources :players, only: [:create, :new, :show, :update] do
      resources :guesses, only: :index
    end
  end
  root to: 'rooms#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/alphanumerically_identifiable.rb
require 'securerandom'

module AlphanumericallyIdentifiable
  extend ActiveSupport::Concern

  def generate(attributes = {})
    attrs = attributes.merge(generate_attributes)
    new(attrs)
  end

  def generate!(attributes = {})
    attrs = attributes.merge(generate_attributes)
    create!(attrs)
  end

  def random_id
    SecureRandom.alphanumeric(10)
  end

  private

  def generate_attributes
    { id: random_id }
  end
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :player
  delegate :room, to: :player
  default_scope { order(:id) }

  after_create_commit -> {
    if room.over?
      room.broadcast_latest_state
    else
      broadcast_append_later_to player, :guesses, target: player
    end
  }

  before_validation { word&.downcase! }

  validates_associated :player,
    on: :create,
    message: "Too many guesses"

  validates :word, inclusion: {
    in: ->(_) { Rails.cache.read(:guesses) },
    message: "Not in word list"
  }

  validates :word, length: {
    minimum: 5,
    maximum: 5,
    too_short: "Not enough letters",
    too_long: "Too many letters"
  }

  def ==(word)
    self.word == word
  end

  def correct?
    evaluations.all?(:correct)
  end

  def evaluations
    GuessEvaluator.new(self.word, room.word).evaluations
  end
end

app/models/player.rb
require 'set'

class Player < ApplicationRecord
  extend AlphanumericallyIdentifiable

  class << self
    def attrs_from_session_token(token)
      token.split(':') => [id, password]
      { id:, password: }
    end

    private

    def generate_attributes
      super.merge(password: random_id)
    end
  end

  MAX_GUESSES ||= 6

  belongs_to :room
  has_many :guesses, dependent: :destroy
  validates :name,
    length: { minimum: 1 },
    allow_nil: true,
    allow_blank: false
  validates :guesses, length: { maximum: MAX_GUESSES - 1 }

  after_create_commit do
    broadcast_append_later_to room,
                              :players,
                              target: :room_boards,
                              partial: 'rooms/board'
  end

  after_update_commit do
    broadcast_update_later_to self,
                              :name,
                              target: "name_player_#{id}",
                              partial: 'players/name'
  end

  def can_guess?
    guesses.count < MAX_GUESSES
  end

  def name
    return super if new_record?
    self[:name] || "Player #{room.players.find_index(self) + 1}"
  end

  def unnamed?
    self[:name].blank?
  end

  def guess(word)
    Guess.create!(
      word: word,
      player: self
    )
  end

  def seen_letters
    guesses.each_with_object({}) do |guess, seen|
      guess.evaluations.each_with_index do |evaluation, i|
        letter = guess.word[i].to_sym
        seen[letter] = evaluation.to_s
      end
    end
  end

  def session_token
    [id, password].join(':')
  end

  def won?
    guesses.any?(&:correct?)
  end

  def broadcast_latest_state
    broadcast_update_later_to self, :guesses
  end
end

app/models/room.rb
class Room < ApplicationRecord
  extend AlphanumericallyIdentifiable

  has_many :players, dependent: :destroy
  has_many :guesses, through: :players

  class << self
    def random_word
      Rails.cache.read(:words).sample
    end

    private

    def generate_attributes
      super.merge(word: random_word)
    end
  end

  def empty?
    players.none?
  end

  def full?
    players.many?
  end

  def won?
    Guess.where(player: players, word: word).any?
  end

  def lost?
    players.none?(&:can_guess?)
  end

  def over?
    won? || lost?
  end

  def winner
    players.find(&:won?)
  end

  def reset!
    clear_guesses
    reset_word
    broadcast_latest_state
  end

  def broadcast_latest_state
    %w{ dashboard form signup }.each &method(:refresh_partial)
    players.each(&:broadcast_latest_state)
  end

  private

  def clear_guesses
    Guess.where(player: players).destroy_all
  end

  def reset_word
    self.word = Room.random_word
    save
  end

  def refresh_partial(partial)
    broadcast_update_later_to(
      self,
      target: "room_#{partial}",
      partial: "rooms/#{partial}",
      locals: { room: self, initial_render: false }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_player, :actionify_for

  private

  def logged_in?
    !!current_player
  end

  def current_player
    return nil unless attrs = current_player_attrs
    @current_player ||= Player.find_by(attrs)
  end

  def actionify_for(stimulus_controller_events)
    stimulus_controller_events.reduce('') do |actions, (controller, events)|
      transformer = events.is_a?(Enumerable) ? :to_actions : :to_action
      actions + send(transformer, controller.to_s.dasherize, events)
    end
  end

  def require_turbo_frame_header
    render status: :forbidden unless is_turbo_frame_request?
  end

  def room_id
    nil
  end

  private

  def current_player_attrs
    return nil unless token = session[room_id]
    Player.attrs_from_session_token(token)
  end

  def is_turbo_frame_request?
    !!request.headers['turbo-frame']
  end

  def to_actions(stimulus_controller, actions)
    actions.map { |action| to_action(stimulus_controller, action) }.join(' ')
  end

  def to_action(stimulus_controller, action)
    "#{action}->#{stimulus_controller}##{action}"
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :require_login, only: :create
  before_action :require_turbo_frame_header

  def index
    player = Player.find(params[:player_id])
    render turbo_stream: turbo_stream.update(
      player,
      target: player,
      template: 'guesses/index',
      locals: {
        player: player,
        is_visible: player_guesses_visible?(player)
      }
    )
  end

  def show
    guess = Guess.find(params[:id])
    render :show, locals: {
      guess: guess,
      is_visible: guess_visible?(guess),
      refresh: false
    }
  end

  def new
    render :new, locals: {
      room: Room.find(room_id),
      guess: Guess.new,
      initial_render: true
    }
  end

  def create
    @room = Room.find(room_id)
    guess = Guess.new(player: current_player, word: params[:word])

    if guess.save
      current_player.guesses.reload
      @guess = Guess.new
    else
      @guess = guess
    end
  end

  private

  def room_id
    params[:room_id]
  end

  def guess_visible?(guess)
    guess.player == current_player || guess.room.over?
  end

  def player_guesses_visible?(player)
    player == current_player || player.room.over?
  end

  def require_login
    render status: :forbidden unless logged_in?
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :require_turbo_frame_header, except: [:create, :update]
  helper_method :get_name

  def create
    @room = Room.find(room_id)
    @player = Player.generate!(room: @room)
    session[room_id] = @player.session_token
  end

  def new
    @room = Room.find(room_id)
  end

  def show
    player = Player.find(params[:id])
    template = can_rename(player) ? 'edit' : 'show'
    render turbo_stream: turbo_stream.update(
      "name_player_#{player.id}",
      template: "players/#{template}",
      locals: { player: }
    )
  end

  def update
    @player = Player.find(params[:id])
    render status: :forbidden unless @player == current_player
    @player.update!(name: params[:name])
    redirect_to room_path(@player.room)
  end

  private

  def room_id
    params[:room_id]
  end

  def can_rename(player)
    player == current_player && player.unnamed?
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room = Room.find(room_id)
    ensure_first_player_exists
    @guess = Guess.new
  end

  def create
    @room = Room.generate!
    redirect_to room_path(@room)
  end

  def update
    @room = Room.find(params[:id])
    @room.reset!
  end

  private

  def room_id
    params[:id]
  end

  def ensure_first_player_exists
    if @room.empty?
      room_id = params[:id]
      player = Player.generate!(room_id: room_id)
      session[room_id] = player.session_token
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/guesses/_empty_row.html.erb
<div class="guess-row">
  <div class="<%= class_names('row', placeholder: placeholder) %>">
    <% 5.times do %>
      <div class="tile" data-state="empty" data-animation="idle"></div>
    <% end %>
  </div>
</div>

app/views/guesses/_guess.html.erb
<%= turbo_frame_tag dom_id(guess),
  src: room_guess_path(guess.room, guess),
  loading: :lazy do %>
  <%= render partial: 'guesses/empty_row', locals: { placeholder: true } %>
<% end %>

app/views/guesses/create.turbo_stream.erb
<%= turbo_stream.update :room_form do %>
  <%= render template: 'guesses/new',
    locals: { room: @room, guess: @guess, initial_render: false } %>
<% end %>
<%= turbo_stream.update :room_keyboard do %>
  <%= render partial: 'rooms/keyboard',
    locals: { room: @room, player: current_player } %>
<% end %>

app/views/guesses/index.html.erb
<% player.guesses.each do |guess| %>
  <%= render template: 'guesses/show',
    locals: { guess: guess, is_visible: is_visible, refresh: true } %>
<% end %>

app/views/guesses/new.html.erb
<%= turbo_stream_from room %>
<%= turbo_frame_tag :room_form do %>
  <% if logged_in? && !room.over? %>
    <% unless initial_render %>
      <div data-controller="guess-row-reset"></div>
    <% end %>
    <%= form_with(
      id: dom_id(room),
      url: room_guesses_path(room.id),
      method: :post
    ) do |f| %>
      <% if guess.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% guess.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.hidden_field(:word, id: 'guess') %>
    <% end %>
  <% end %>
<% end %>

app/views/guesses/show.html.erb
<%= turbo_frame_tag dom_id(guess) do %>
  <div class="guess-row non-empty"
    data-controller="guess"
    data-guess-origin-value="<%= refresh ? 'refresh' : 'reveal' %>">
    <div class="row" data-guess-target="row">
      <% guess.evaluations.map.with_index do |evaluation, i| %>
        <div class="tile" data-state="<%= evaluation %>" data-animation="idle">
          <%= is_visible ? guess.word[i] : '' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wordle With Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= yield :head %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_game.html.erb
<div class="game">
  <div class="board-container">
    <!-- TODO: fixed height hack -->
    <div class="board" style="width: 303px; height: 355px;">
      <%= turbo_stream_from player %>
      <%= turbo_frame_tag dom_id(player) do %>
        <%= render player.guesses %>
      <% end %>
      <% (Player::MAX_GUESSES - player.guesses.size).times do %>
        <%= render partial: 'guesses/empty_row' %>
      <% end %>
    </div>
  </div>
</div>

app/views/players/_name.html.erb
<%= turbo_stream_from player, :name %>
<%= turbo_frame_tag dom_id(player, :name),
  src: room_player_path(player.room, player),
  loading: :lazy do %>
  <div class="player-name">
    <h2 class="placeholder">&nbsp;</h2>
  </div>
<% end %>

app/views/players/_player.html.erb
<%= render partial: 'players/name', locals: { player: player } %>

<%= turbo_stream_from player, :guesses %>
<%= turbo_frame_tag dom_id(player),
  src: room_player_guesses_path(player.room, player) %>

<div id="<%= dom_id(player, :empty_rows) %>">
  <% # TODO: CSS hack %>
  <% Player::MAX_GUESSES.times do %>
    <%= render partial: 'guesses/empty_row', locals: { placeholder: false } %>
  <% end %>
</div>

app/views/players/_seen_letters.html.erb
<% player.seen_letters.each do |type, letters| %>
  <p>
    <strong><%= type.to_s.capitalize %>:</strong>
    <%= letters.join(', ') %>
  </p>
<% end %>

app/views/players/create.turbo_stream.erb
<%= turbo_stream.remove :room_signup %>
<%= turbo_stream.append :room_form do %>
  <%= render partial: 'rooms/form', locals: { room: @room } %>
<% end %>
<%= turbo_stream.update :room_keyboard do %>
  <%= render partial: 'rooms/keyboard',
    locals: { room: @room, player: @player } %>
<% end %>

app/views/players/edit.html.erb
<%= turbo_stream_from player, :name %>
<%= turbo_frame_tag dom_id(player, :name) do %>
  <div data-controller="player-name" class="player-name">
    <%= form_with(
      url: room_player_path(player.room, player.id),
      method: :patch
    ) do |f| %>
      <%= f.hidden_field(
        :name,
        'data-player-name-target' => 'input',
        value: player.name)
      %>
    <% end %>
    <h2 class="<%= class_names('editable', unnamed: player.unnamed?) %>"
      data-action="<%= actionify_for player_name: %w{click keydown blur} %>"
      data-player-name-target="name"
    ><%= player.name %></h2>
  </div>
<% end %>

app/views/players/new.html.erb
<%= turbo_stream_from @room %>
<%= turbo_frame_tag :room_signup do %>
  <% if !@room.over? && !logged_in? %>
    <%= button_to 'Join Game',
      room_players_path(@room.id),
      class: 'btn btn-primary',
      method: :post %>
    <hr>
  <% end %>
<% end %>

app/views/players/show.html.erb
<div class="player-name">
  <h2 class="<%= class_names(unnamed: player.unnamed?) %>">
    <%= player.name %>
  </h2>
</div>

app/views/rooms/_board.html.erb
<div class="game">
  <div class="board-container">
    <div class="board">
      <%= render player %>
    </div>
  </div>
</div>

app/views/rooms/_dashboard.html.erb
<%= turbo_frame_tag :room_dashboard do %>
  <% if room.over? %>
    <% unless initial_render %>
      <div data-controller="guess-row-reset"></div>
    <% end %>
    <h3 id="end-banner"><%= room.won? ? 'Solved!' : 'Game over!' %></h3>
    
    <% if room.lost? %><p>Word was: <b><%= room.word %></b></p><% end %>
    <%= button_to 'New Word',
      room_path(room.id),
      class: 'btn btn-primary',
      method: :patch %>
    <% if room.won? %>
      <div data-controller="share">
        <button data-action="<%= actionify_for share: 'click' %>"
          class="btn btn-primary">
          Share
          <%= render partial: 'rooms/share_icon' %>
        </button>
      </div>
    <% end %>
  <% else %>
    <% unless initial_render %>
      <div data-controller="keyboard-reset"></div>
    <% end %>
  <% end %>
<% end %>

app/views/rooms/_form.html.erb
<%= turbo_frame_tag :room_form, src: new_room_guess_path(room) %>

app/views/rooms/_keyboard.html.erb
<%
  keyboard = [
    %i{ q w e r t y u i o p },
     %i{ a s d f g h j k l },
     %i{ ↵ z x c v b n m ← }
  ]
%>

<div id="keyboard"
  data-controller="keyboard"
  data-keyboard-player-id-value="<%= player.id %>">
  <% keyboard.each do |row| %>
    <div class="row">
      <% if row.count < 10 %><div class="spacer half"></div><% end %>
        <% row.each do |key| %>
          <% key_class_names = class_names(
            player.seen_letters.fetch(key, nil),
            'one-and-a-half' => [:↵, :←].include?(key)
          ) %>
          <button data-key="<%= key %>"
            data-action="<%= actionify_for keyboard: 'click' %>"
            class="<%= key_class_names %>">
            <%= key == :↵ ? 'enter' : key %>
          </button>
        <% end %>
      <% if row.count < 10 %><div class="spacer half"></div><% end %>
    </div>
  <% end %>
</div>

app/views/rooms/_share_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
  <path fill="var(--white)" d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92s2.92-1.31 2.92-2.92c0-1.61-1.31-2.92-2.92-2.92zM18 4c.55 0 1 .45 1 1s-.45 1-1 1-1-.45-1-1 .45-1 1-1zM6 13c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1zm12 7.02c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1z"></path>
</svg>

app/views/rooms/_signup.html.erb
<%= turbo_frame_tag :room_signup, src: new_room_player_path(room) %>

app/views/rooms/show.html.erb
<div class="container">
  <h1>Wordle With Friends</h1>

  <%= turbo_stream_from @room %>
  <%= turbo_frame_tag :room_dashboard do %>
    <%= render partial: 'dashboard',
      locals: { room: @room, initial_render: true } %>
  <% end %>

  <%= turbo_frame_tag :room_signup do %>
    <%= render template: 'players/new' %>
  <% end %>

  <%= turbo_frame_tag :room_form do %>
    <%= render template: 'guesses/new',
      locals: { room: @room, guess: Guess.new, initial_render: false } %>
  <% end %>

  <%= turbo_stream_from @room, :players %>
  <%= turbo_frame_tag :room_boards do %>
    <%= render partial: 'board',
      collection: @room.players,
      as: :player %>
  <% end %>

  <%= turbo_frame_tag :room_keyboard do %>
    <% if current_player %>
      <%= render partial: 'keyboard',
        locals: { room: @room, player: current_player } %>
    <% end %>
  <% end %>
</div>